### PR TITLE
Final version EN and FR

### PR DESCRIPTION
**Pull request by toch**
It includes:
- translation in FR
- some minor modifications and corrections in EN
- a mandatory statement about the fee

### CODE REVIEW

**Comment by hannesfostie** [comment]
I was bombarded to be the treasurer? :P Is that a mistake or... ? I'm the worst with administration/money :D

**Comment by toch** [comment]
@hannesfostie Sorry mistake, Joren is, I'll fix that tomorrow.

**Comment by oana-sipos** [comment]
No comments from my side. All good.

**Comment by toch** [comment]
@hannesfostie done, sorry for the mistake, I dunno what happened in my mind. thanks for the review

@oana-sipos thanks for the review

Could one of you merge it then?

**Pull request merged**
