### PR TITLE
Title II: Member, Admission, Termination

### PR DESCRIPTION
**Pull request by toch**
Let's discuss here the Title II: Member, Admission, Termination

### CODE REVIEW

**Comment by oana-sipos** [comment]
Rough ideas:

Member: do we keep it open and anybody can easily become a member? Or do we want to make them pay a fee and make it more restrictive? 

I would go for the open, yet, find a way for people to feel as members: make them sign up on a page (something like what there is now for BRUG.be).

Admission: Not sure what you meant here. I would say that there should be more regulation to who & how can become a board member, rather than how to accept members.

Termination: I would say that as long as at least one of the founders wants to go on working and keeping up the NGO, it should still be on. If, at any moment, there is no one who wants to be in charge and work for the organization + there is no interested members for a period of x months (although this sounds vague), then it is a point when disolving it should be taken into account.

**Comment by toch** [comment]
@oana-sipos did you see the suggestion made https://github.com/brug-be/statute/pull/2/files ?

**Comment by toch** [comment]
@oana-sipos's comment (received by email):
- currently we have 3 statuses for members: associate, full and sponsor. I would not call sponsor members as a status (I would keep members separate from sponsorship, and not mix them). However, I would still add a third category and that would be board member. What do you think?
- I would make clearer the regulations regarding how an associate member can become full (instead of majority I would mention 1/2 of votes or a percentage anyway + mention in what kind of meetings can this happen - regular or general assemblies)
- there is no specification on the number of votes needed to expel a member (2/3 is usually a good ratio I guess)

**Comment by toch** [comment]
about different kinds of member:
Ok to get rid of sponsor member. Not necessary to introduce a board member, a board member is just a full member elected to be part of the board.

**Comment by toch** [comment]
> I would make clearer the regulations regarding how an associate member can become full (instead of majority I would mention 1/2 of votes or a percentage anyway + mention in what kind of meetings can this happen - regular or general assemblies)

A majority is a subset of a set consisting of more than half of the set's elements. Not necessary to make it more precise, it is already.

**Comment by toch** [comment]
> there is no specification on the number of votes needed to expel a member (2/3 is usually a good ratio I guess)

I is:

```
The decision of the general assembly must be taken by a majority of two thirds
of votes of the members present or represented, but no quorum is required;
```

**Pull request merged**
